Per 9743 replace vagrant with docker
PermanentOrg/devenv pull request #71
Opened 2024-08-08 12:40 UTC by valentinvsp

2024-08-12 20:39 UTC, cecilia-donnelly requested changes
Can you update the README to describe how to use this version?

2024-08-14 00:08 UTC, liam-lloyd reviewed
When I run this locally, the API appears to work (though I haven't tested exhaustively), but the daemons don't. This appears to be because [this check](https://github.com/PermanentOrg/back-end/blob/626e4f2a37412d3dfee7f4cb8e1f5af1b3001b29/daemon/index.php#L73) always fails.

2024-08-14 08:58 UTC, valentinvsp commented on docker-compose.yml
> -version: "3.7"
afaik docker compose file versioning has been deprecated and you should get some warning in the logs if you still have it

2024-08-14 08:59 UTC, valentinvsp commented on docker-compose.yml
> +        # TODO -> update condition to healty
in an ideal scenario, but not necessary. would need to define a rule for condition healthy

2024-08-14 09:00 UTC, valentinvsp commented on docker-compose.yml
> +      - ../back-end/api:/data/www/api
hm... that makes sense. would also need to exec into the container and restart the service as well

2024-08-14 09:03 UTC, valentinvsp commented
> Can you update the README to describe how to use this version?

done

2024-08-14 21:01 UTC, cecilia-donnelly commented
Thanks for getting this to such a good place @valentinvsp ! Closing now with the expectation that @liam-lloyd will pick it up as PER-9787 in October.

2024-08-14 21:02 UTC, closed without merging